policies:
  - type: commit
    spec:
      header:
        length: 89
        imperative: true
        case: lower
        invalidLastCharacters: .
      body:
        required: true
      spellcheck:
        locale: US
      maximumOfOneCommit: false
      conventional:
        types:
          - feat
          - fix
          - chore
          - docs
          - perf
          - refactor
          - style
          - test
          - release
        scopes:
          - .*
