package models

import (
	"time"
)

type (
	// Snippet model.
	Snippet struct {
		// Create - date of snippet creation.
		Created time.Time
		// Expires - date of snippet expiration.
		Expires time.Time
		// Title - snippet title.
		Title string
		// Content - snippet content.
		Content string
		// ID - snippet autogenerated ID.
		ID int
	}
)
