package models

import (
	"time"
)

type (
	// User model.
	User struct {
		// Name - username.
		Name string
		// Email - user email address. Unique.
		Email string
		// Created - user creation date.
		Created time.Time
		// HashedPassword - user password stored as hash.
		HashedPassword []byte
		// ID - user autogenerated ID.
		ID int
	}
)
